version: "3.7"
services:
  frontend:
    image: docker.pkg.github.com/meidor/babypoll/frontend:latest
    networks:
      - default
      - traefik-public
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      labels:
        - traefik.frontend.rule=Host:poll.har.ink,poll.ditzel.dev
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
  backend:
    image: docker.pkg.github.com/meidor/babypoll/backend:latest
    networks:
      - default
      - traefik-public
    volumes:
      - dbvolume:/app/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      labels:
        - traefik.frontend.rule=Host:poll.har.ink;PathPrefix:/api
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
networks:
  default:
  traefik-public:
    external: true
volumes:
  dbvolume:
