version: "3.7"
services:
  frontend:
    build:
      context: .
      dockerfile: DockerfileBabypoll
      args:
        api_base_url: https://${DOMAIN?Variable DOMAIN not set}
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  backend:
    build:
      context: .
      dockerfile: DockerfileBabypollBackend
    networks:
      - default
    volumes:
      - dbvolume:/app/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  default:
volumes:
  dbvolume:
